### ISSUE TITLE
Make all header properties lower case

### ISSUE THREAD

**Issue by chamini2** [davesag/mock-req-res#28]
In express after receiving the headers they turn them all lower case since they are case insensitive. Can we do the same for this mock?

**Comment by davesag** [comment]
The express request object doesn’t actually change the headers you set, it just does a case insensitive search when you call req.get(‘some-header’) and since, in the mock, get is just a stub, you can tell it to respond with whatever you like.

(Sorry for poor formatting in this reply, I’m on my phone)

The mock has no associated logic at all, it just gives you a container to use and customise how you like.

Cheers 

Dave
